const SUPABASE_URL = 'https://ttqxhrxrkewmyyiqaafn.supabase.co';
const BUCKET       = 'Projects';
const HERO_BUCKET  = 'Hero';

export function storageUrl(path) {
  return `${SUPABASE_URL}/storage/v1/object/public/${BUCKET}/${path}`;
}

function heroUrl(path) {
  return `${SUPABASE_URL}/storage/v1/object/public/${HERO_BUCKET}/${path}`;
}

// ─── Hero rotating backgrounds ────────────────────────────────────────────────
export const HERO_IMAGES = [
  { src: heroUrl('hero-images/LakeForest.png'),             alt: 'Lake Forest residence' },
  { src: heroUrl('hero-images/LakeForestFoyer.png'),        alt: 'Lake Forest foyer' },
  { src: heroUrl('hero-images/LakeForestMasterBedroom.png'),alt: 'Lake Forest master bedroom' },
  { src: heroUrl('hero-images/LakeSide0474.jpg'),           alt: 'Lakeside estate' },
  { src: heroUrl('hero-images/LakeSide0479.jpg'),           alt: 'Lakeside interior' },
  { src: heroUrl('hero-images/LakeSide0485.jpg'),           alt: 'Lakeside living' },
];

// ─── Residences section — all 8 projects ─────────────────────────────────────
export const PROJECTS = [
  {
    id: '01',
    slug: 'the-four-seasons-residences',
    title: 'The Four Seasons Residences',
    location: 'Chicago, Illinois',
    year: '2024',
    category: 'Luxury High-Rise',
    description:
      "A full-floor residence within one of Chicago's most celebrated buildings. The interiors negotiate the extraordinary with the intimate — Venetian plaster, aged brass, and stone drawn from a single quarry compose rooms of unhurried authority.",
    cover: storageUrl('the-four-seasons-residences/four-seasons-01.jpg'),
    gallery: [
      storageUrl('the-four-seasons-residences/four-seasons-02.jpg'),
      storageUrl('the-four-seasons-residences/four-seasons-03.jpg'),
      storageUrl('the-four-seasons-residences/four-seasons-04.jpg'),
      storageUrl('the-four-seasons-residences/four-seasons-05.jpg'),
      storageUrl('the-four-seasons-residences/four-seasons-06.jpg'),
      storageUrl('the-four-seasons-residences/four-seasons-07.jpg'),
    ],
  },
  {
    id: '02',
    slug: 'sunset-lane',
    title: 'Sunset Lane',
    location: 'Lake Forest, Illinois',
    year: '2024',
    category: 'Private Residence',
    description:
      'A gracious North Shore estate conceived as a study in natural materials and composed restraint. Linen, limestone, and hand-hewn oak respond to the quality of Midwestern light — warm in winter, abundant in summer.',
    cover: storageUrl('sunset-lane/sunsetlane01.jpg'),
    gallery: [
      storageUrl('sunset-lane/SunsetLane-02.jpg'),
      storageUrl('sunset-lane/SunsetLane-03.jpg'),
      storageUrl('sunset-lane/SunsetLane-04.jpg'),
      storageUrl('sunset-lane/SunsetLane-06.jpg'),
      storageUrl('sunset-lane/SunsetLane-08.jpg'),
      storageUrl('sunset-lane/SunsetLane-09.jpg'),
      storageUrl('sunset-lane/SunsetLane-10.jpg'),
      storageUrl('sunset-lane/SunsetLane-11.jpg'),
      storageUrl('sunset-lane/SunsetLane-12.jpg'),
      storageUrl('sunset-lane/SunsetLane-13.jpg'),
      storageUrl('sunset-lane/SunsetLane-14.jpg'),
      storageUrl('sunset-lane/SunsetLane-16.jpg'),
      storageUrl('sunset-lane/SunsetLane-18.jpg'),
      storageUrl('sunset-lane/SunsetLane-19.jpg'),
      storageUrl('sunset-lane/SunsetLane-20.jpg'),
      storageUrl('sunset-lane/SunsetLane-21.jpg'),
      storageUrl('sunset-lane/SunsetLane-22.jpg'),
      storageUrl('sunset-lane/SunsetLane-23.jpg'),
      storageUrl('sunset-lane/sunsetlane05.jpg'),
      storageUrl('sunset-lane/sunsetlane07.jpg'),
    ],
  },
  {
    id: '03',
    slug: 'lakeside',
    title: 'Lakeside',
    location: 'Lake Michigan, Michigan',
    year: '2023',
    category: 'Lakeside Estate',
    description:
      'A summer residence on the eastern shore of Lake Michigan, designed to dissolve the boundary between interior and landscape. Bleached oak, raw concrete, and palette borrowed entirely from dune grass, water, and sky.',
    cover: storageUrl('lakeside/LakeSide0472.jpg'),
    gallery: [
      storageUrl('lakeside/LakeSide0474.jpg'),
      storageUrl('lakeside/LakeSide0475.jpg'),
      storageUrl('lakeside/LakeSide0476.jpg'),
      storageUrl('lakeside/LakeSide0477.jpg'),
      storageUrl('lakeside/LakeSide0478.jpg'),
      storageUrl('lakeside/LakeSide0479.jpg'),
      storageUrl('lakeside/LakeSide0480.jpg'),
      storageUrl('lakeside/LakeSide0481.jpg'),
      storageUrl('lakeside/LakeSide0482.jpg'),
      storageUrl('lakeside/LakeSide0483.jpg'),
      storageUrl('lakeside/LakeSide0484.jpg'),
      storageUrl('lakeside/LakeSide0485.jpg'),
      storageUrl('lakeside/LakeSide0486.jpg'),
      storageUrl('lakeside/LakeSide0487.jpg'),
      storageUrl('lakeside/LakeSide0488.jpg'),
      storageUrl('lakeside/LakeSide0489.jpg'),
      storageUrl('lakeside/LakeSide0490.jpg'),
      storageUrl('lakeside/LakeSide0491.jpg'),
      storageUrl('lakeside/LakeSide0492.jpg'),
      storageUrl('lakeside/LakeSide0493.jpg'),
      storageUrl('lakeside/LakeSide0494.jpg'),
      storageUrl('lakeside/LakeSide0495.jpg'),
      storageUrl('lakeside/LakeSide0496.jpg'),
      storageUrl('lakeside/LakeSide0497.jpg'),
      storageUrl('lakeside/LakeSide0498.jpg'),
      storageUrl('lakeside/LakeSide0499.jpg'),
      storageUrl('lakeside/LakeSide0500.jpg'),
      storageUrl('lakeside/LakeSide0501.jpg'),
      storageUrl('lakeside/LakeSide0503.jpg'),
      storageUrl('lakeside/LakesideMI.jpg'),
    ],
  },
  {
    id: '04',
    slug: 'highland-park',
    title: 'Highland Park',
    location: 'Highland Park, Illinois',
    year: '2023',
    category: 'Suburban Residence',
    description:
      "A complete interior commission in Highland Park's historic district. Every room considered as part of a coherent whole — proportions studied, materials selected for their relationship to light, and each detail resolved against the architecture.",
    cover: storageUrl('highland-park/HighlandPark7.jpg'),
    gallery: [
      // HighlandPark4 removed — exact duplicate of HighlandPark2 (same bytes)
      // HighlandPark9–20 removed — thumbnail quality (21–56 KB vs 130–411 KB)
      storageUrl('highland-park/HighlandPark1.jpg'),
      storageUrl('highland-park/HighlandPark2.jpg'),
      storageUrl('highland-park/HighlandPark3.jpg'),
      storageUrl('highland-park/HighlandPark5.jpg'),
      storageUrl('highland-park/HighlandPark6.jpg'),
      storageUrl('highland-park/HighlandPark8.jpg'),
    ],
  },
  {
    id: '05',
    slug: 'rancho-mirage',
    title: 'Rancho Mirage',
    location: 'Rancho Mirage, California',
    year: '2022',
    category: 'Desert Estate',
    description:
      'A Californian desert estate at the Villaggio Place development. The palette is drawn from the Sonoran landscape — terracotta, sage, and raw steel — while the scale remains quietly domestic, resisting the temptation of spectacle.',
    cover: storageUrl('rancho-mirage/RanchoMirage-VillagioPlace-32.png'),
    gallery: [
      storageUrl('rancho-mirage/RanchoMirage-VillagioPlace-33.png'),
      storageUrl('rancho-mirage/RanchoMirage-VillagioPlace-34.png'),
      storageUrl('rancho-mirage/RanchoMirage-VillagioPlace-35.png'),
      storageUrl('rancho-mirage/RanchoMirage-VillagioPlace-36.png'),
      storageUrl('rancho-mirage/RanchoMirage-VillagioPlace-37.png'),
      storageUrl('rancho-mirage/RanchoMirage-VillagioPlace-38.png'),
      storageUrl('rancho-mirage/RanchoMirage-VillagioPlace-39.png'),
      storageUrl('rancho-mirage/RanchoMirage-VillagioPlace-40.png'),
      storageUrl('rancho-mirage/RanchoMirage-VillagioPlace-41.png'),
      storageUrl('rancho-mirage/RanchoMirage-VillagioPlace-42.png'),
      storageUrl('rancho-mirage/RanchoMirage-VillagioPlace-43.png'),
      storageUrl('rancho-mirage/RanchoMirage-VillagioPlace-44.png'),
      storageUrl('rancho-mirage/RanchoMirage-VillagioPlace-45.png'),
      storageUrl('rancho-mirage/RanchoMirage-VillagioPlace-46.png'),
      storageUrl('rancho-mirage/RanchoMirage-VillagioPlace-49.png'),
      storageUrl('rancho-mirage/RanchoMirage-VillagioPlace-50.png'),
      storageUrl('rancho-mirage/RanchoMirage-VillagioPlace-51.png'),
      storageUrl('rancho-mirage/RanchoMirage-VillagioPlace-52.png'),
      storageUrl('rancho-mirage/RanchoMirage-VillagioPlace-53.png'),
      storageUrl('rancho-mirage/RanchoMirage-VillagioPlace-55.png'),
      storageUrl('rancho-mirage/RanchoMirage-VillagioPlace-56.png'),
      storageUrl('rancho-mirage/RanchoMirage-VillagioPlace-57.png'),
      storageUrl('rancho-mirage/RanchoMirage-VillagioPlace-58.png'),
      storageUrl('rancho-mirage/RanchoMirage-VillagioPlace-59.png'),
      storageUrl('rancho-mirage/RanchoMirage-VillagioPlace-60.png'),
      storageUrl('rancho-mirage/RanchoMirage-VillagioPlace-61.png'),
      storageUrl('rancho-mirage/RanchoMirage-VillagioPlace-63.png'),
      storageUrl('rancho-mirage/RanchoMirage-VillagioPlace-66.png'),
      storageUrl('rancho-mirage/RanchoMirage-VillagioPlace-67.png'),
      storageUrl('rancho-mirage/RanchoMirage-VillagioPlace-68.png'),
      storageUrl('rancho-mirage/RanchoMirage-VillagioPlace-69.png'),
      storageUrl('rancho-mirage/ranchomirage.png'),
      storageUrl('rancho-mirage/ranchomirage2.png'),
      storageUrl('rancho-mirage/ranchomirage3.png'),
    ],
  },
  {
    id: '06',
    slug: 'halco-dunes',
    title: 'Halco Dunes',
    location: 'Michigan City, Indiana',
    year: '2022',
    category: 'Dunes Residence',
    description:
      'A dunes retreat on the southern shore of Lake Michigan. Sand, cedar, and weathered steel form a home that reads as inevitable against its landscape — as though it arrived not by design but by geological time.',
    cover: storageUrl('halco-dunes/HalcoDunes.jpeg'),
    gallery: [
      storageUrl('halco-dunes/HalcoDunes2.jpeg'),
      storageUrl('halco-dunes/HalcoDunes3.jpeg'),
      storageUrl('halco-dunes/HalcoDunes4.jpeg'),
      storageUrl('halco-dunes/HalcoDunes5.jpeg'),
      storageUrl('halco-dunes/HalcoDunes6.jpeg'),
    ],
  },
  {
    id: '07',
    slug: 'w-winona',
    title: 'W. Winona',
    location: 'Chicago, Illinois',
    year: '2022',
    category: 'Urban Residence',
    description:
      'A Chicago greystone reimagined from structure outward. The original architecture demanded restraint — no element added that the building did not already suggest. The result is a city home of genuine character and uncommon quiet.',
    cover: storageUrl('w-winona/Winona.png'),
    gallery: [
      storageUrl('w-winona/Winona1.png'),
      storageUrl('w-winona/Winona2.png'),
      storageUrl('w-winona/Winona3.png'),
      storageUrl('w-winona/Winona4.png'),
      storageUrl('w-winona/Winona5.png'),
      storageUrl('w-winona/Winona6.png'),
      storageUrl('w-winona/Winona7.png'),
      storageUrl('w-winona/Winona8.png'),
      storageUrl('w-winona/Winona9.png'),
      storageUrl('w-winona/Winona10.png'),
      storageUrl('w-winona/Winona11.png'),
      storageUrl('w-winona/Winona12.png'),
    ],
  },
];

// ─── Philosophy section image ─────────────────────────────────────────────────
export const PHILOSOPHY_IMAGE = storageUrl('lakeside/LakeSide0477.jpg');
